[versions]
kotlin = "1.7.20-Beta"
coroutines = "1.6.4"
serialization = "1.4.0-RC"
kotest = "5.4.2"

[libraries]
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "serialization" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.4.0" }
mockk = { module = "io.mockk:mockk-common", version = "1.12.5" }
kotlin-logging = { module = "io.github.microutils:kotlin-logging", version = "2.1.23" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
kotest-framework-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-framework-datatest = { module = "io.kotest:kotest-framework-datatest", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version = "2.0.0" }
arrow-core = { module = "io.arrow-kt:arrow-core", version = "1.0.1" }
uuid = { module = "com.benasher44:uuid", version = "0.5.0" }

[bundles]
kotlin = ["kotlinx-serialization", "kotlinx-datetime", "kotlinx-coroutines"]
kotest = ["kotest-assertions-core", "kotest-property", "kotest-framework-engine", "kotest-framework-datatest"]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version = "1.7.10" }